#ifndef FORMATS_H
#define FORMATS_H

enum RESOURCE_DATA_FORMAT {
	RESOURCE_DATA_FORMAT_UNKNOWN,
	RESOURCE_DATA_FORMAT_R32G32B32A32_FLOAT,
	RESOURCE_DATA_FORMAT_R32G32B32_FLOAT,
	RESOURCE_DATA_FORMAT_R32G32_FLOAT,
	RESOURCE_DATA_FORMAT_R16_UINT,
	RESOURCE_DATA_FORMAT_R32_UINT,
	RESOURCE_DATA_FORMAT_COUNT
};

enum PRIMITIVE_TOPOLOGY_TYPE {
	PRIMITIVE_TOPOLOGY_TYPE_POINTLIST,
	PRIMITIVE_TOPOLOGY_TYPE_LINELIST,
	PRIMITIVE_TOPOLOGY_TYPE_LINESTRIP,
	PRIMITIVE_TOPOLOGY_TYPE_TRIANGLELIST,
	PRIMITIVE_TOPOLOGY_TYPE_TRIANGLESTRIP,
	PRIMITIVE_TOPOLOGY_TYPE_COUNT
};

enum MAP_TYPE {
	MAP_READ,
	MAP_WRITE,
	MAP_READ_WRITE,
	MAP_WRITE_DISCARD,
	MAP_WRITE_NO_OVERWRITE,
	MAP_COUNT
};

#endif // !FORMATS_H