#ifndef FORMATS_H
#define FORMATS_H

enum RESOURCE_DATA_FORMAT {
	RESOURCE_DATA_FORMAT_UNKNOWN,
	RESOURCE_DATA_FORMAT_R32G32B32A32_FLOAT,
	RESOURCE_DATA_FORMAT_R32G32B32_FLOAT,
	RESOURCE_DATA_FORMAT_R32G32_FLOAT,
	RESOURCE_DATA_FORMAT_R16_UINT,
	RESOURCE_DATA_FORMAT_R32_UINT,
	RESOURCE_DATA_FORMAT_COUNT
};

#endif // !FORMATS_H